Getting started readme
mcarpenter622/ebitenui pull request #75
Opened 2023-06-04 09:28 UTC by NickGowdy

When I first forked the repo, I wasn't sure how to run the codebase locally. I figured it out by looking at `.vscode/launch.json` and seeing the command it runs inside VS code.

I think it would be better overall if we have some examples of how to run the code locally for everybody as not all devs use VS Code. 

I've also added a contributing section as we didn't have one. However it's very basic and I'm not sure how much detail we should include.

2023-06-04 09:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ebitenui/ebitenui?pullRequest=75) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ebitenui/ebitenui?pullRequest=75) before we can accept your contribution.<br/><hr/>**Nick Gowdy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ebitenui/ebitenui?pullRequest=75) it.</sub>

2023-06-04 15:39 UTC, mcarpenter622 requested changes
Hey Nick, Thank you for the PR. I have a couple requests for ya, and can you please sign the CLA from the bot =)

2023-06-04 15:39 UTC, mcarpenter622 commented on README.md
> +There are Ebiten UI examples that can be found in the `_examples/` folder. Here are some example of how to run them locally:
This is great, but can you please add a small section about how these commands must be run from the root directory of the project else they won't work?

2023-06-04 15:39 UTC, mcarpenter622 commented on README.md
> +Want to help develop Ebiten UI? Check out our [current issues](https://github.com/ebitenui/ebitenui/issues). Want to know the steps on how to start contributing, take a look at the [open source guide
What do you think about updating the link for the open source guide to : https://opensource.guide/how-to-contribute/

2023-06-13 01:26 UTC, mcarpenter622 commented
Could you also please add a section about running the examples as a wasm:
From root:
go run github.com/hajimehoshi/wasmserve@latest ./_examples/widget_demos/textinput

Open browser to localhost:8080

2023-06-25 22:41 UTC, mcarpenter622 commented
Hey @NickGowdy are you going to update this? Let me know if not and I'll clean this PR up to get it in and closed.

2023-06-27 13:48 UTC, NickGowdy commented
> Hey Nick, Thank you for the PR. I have a couple requests for ya, and can you please sign the CLA from the bot =)

Hey @mcarpenter622 , I've signed the CLA multiple times and it hasn't changed the workflow approval message. Is there something I'm missing?

2023-06-27 14:27 UTC, mcarpenter622 commented
I am not really sure? Regardless of the bot, if you make the requested changes I can merge the change. I did update it a little while back to a new version which invalidated everyone's previous acceptance. It may be something related to that

2023-08-13 01:34 UTC, mcarpenter622 commented
@NickGowdy  Since it's been a while, I went ahead and incorporated the ideas from this PR. I am going to close this PR for now. Thank you for your contribution!

2023-08-13 01:34 UTC, closed without merging